version: '3.8'

services:
  server:
    container_name: server
    image: server
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - "8080:8080"
    networks:
      - netbridge
    environment:
      - PORT=8080

  client:
    container_name: client  
    image: client
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client      
    ports:
      - "8081:8081"      
    depends_on:
      - server
    networks:
      - netbridge
    environment:
      - SERVER_URL=ws://server:8080/ws
      - PORT=8081

networks:
  netbridge:
